[package]
name = "llm-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true